files:
  - source: /locales/ja-JP.yml
    translation: /locales/%locale%.yml
    update_option: update_as_unapproved
    skip_untranslated_strings: true
  - source: /content/ja/docs/**/*.*
    translation: /content/%two_letters_code%/docs/**/%original_file_name%
    update_option: update_as_unapproved
    skip_untranslated_files: true
    ignore:
      - "/content/ja/docs/**/_*.md"
    languages_mapping:
      two_letters_code:
        zh-TW: tw
        zh-CN: cn
